#ifndef LIBJSONPATH_CONFIG_H
#define LIBJSONPATH_CONFIG_H
#define LIBJSONPATH_VERSION "0.1.0"
#define LIBJSONPATH_VERSION_MAJOR 0
#define LIBJSONPATH_VERSION_MINOR 1
#define LIBJSONPATH_VERSION_PATCH 0
#endif
